name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}' # Replace with the name of your GitHub Actions secret
      - name: google-docs-to-github
        # You may pin to the exact commit or the version.
        # uses: r7kamura/google-docs-to-github@fb3689efb9d4f4ac48231f6000953fd71b460ccd
        uses: r7kamura/google-docs-to-github@v0.1.0
        with:
          # ID of the Google Drive folder to be exported.
          google_drive_folder_id: 1Enofzz7jlcF5vVqLMAf8bVtVCZ9SYBpQ


